# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': '客户', 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='call',
            options={'verbose_name': '通话', 'verbose_name_plural': '通话'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': '联系人', 'verbose_name_plural': '联系人'},
        ),
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name': '线索', 'verbose_name_plural': '线索'},
        ),
        migrations.AlterModelOptions(
            name='potentials',
            options={'verbose_name': '商机', 'verbose_name_plural': '商机'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
        migrations.AddField(
            model_name='call',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Leads', verbose_name='线索'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Leads', verbose_name='线索'),
        ),
    ]
