# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190322_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentials',
            name='stage',
            field=models.CharField(choices=[('10%', '需求分析'), ('25%', '价值建议'), ('50%', '确定决策者'), ('75%', '提案/报价'), ('100%', '成交')], max_length=16, verbose_name='阶段'),
        ),
    ]
