# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_permission_icon'),
        ('crm', '0003_auto_20190326_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(to='rbac.Role', verbose_name='用户角色'),
        ),
    ]
